### PR TITLE
New fact: 1.6M unique logins

### PR DESCRIPTION
**Pull request by RubeVi**

### CODE REVIEW

**Comment by Matic0B** [comment]
Branch has conflicts since there were some recent updates. It would also be great if you could provide a link of where you got that information.

**Comment by RubeVi** [comment]
https://oc.tc/stats?time=eternity&game=global multiply 20x82827 (number of pages)

**Comment by Matic0B** [comment]
But if you go to the last page theres 1454965 on the left of the table

**Comment by RubeVi** [comment]
Oh, Electroid said something about that 

> we have created for the 1.7 million players

https://oc.tc/forums/posts/58767efec296352bd4000043

**Pull request closed without merging**
